### ISSUE TITLE
Saas Check In

### ISSUE THREAD

**Issue by baut0015** [baut0015/saas-website#1]
So far I've worked on my index and tour files, Tour is missing the table and index just needs media queries fixing (worked only on 320px sizing.) However, I am encountering a problem in the Nav disappearing after medium size screen and I was wondering how do I fix that?
(It was difficult already for me to make it toggle from the hamburger as that is a new field for me haha) Thanks!
@muxlowc

**Comment by muxlowc** [comment]
@baut0015  it looks like you have a display: none on your ul in your main.css. So that is just hiding your desktop nav links :).

Have you looked at my none javascript version? It will need alot of tweaks, but it could start as a base should you not want to use javascript lol
https://codepen.io/cmuxlow/pen/wvKvqQM

Good job so far though!
